"""Governed semantic-layer discovery and query primitives.

The package root is intentionally an export surface only. Domain, response,
policy, and backend concerns live in dependency-directed leaf modules so adding
a hosted-only feature cannot accidentally import MetricFlow or a SQL dialect.
"""

from ...guards import PII_BLOCK_CONFIDENCE
from ...semantic_catalog import (
    DIMENSIONS_PER_DECLARATION,
    DIMENSIONS_PER_QUERYABLE_PATH,
    DimensionInfo,
    EntityInfo,
    EntityRole,
    MeasureInfo,
    MetricComposition,
    MetricInfo,
    SemanticCatalogView,
    SemanticModelInfo,
    derive_entity_type,
    merge_element_fields,
    qualified_dimension,
)
from .backend import (
    EXECUTION_DEX,
    EXECUTION_VENDOR,
    BackendDescriptor,
    SemanticBackend,
    SemanticBackendError,
    SemanticLayer,
    SemanticLayerError,
    SemanticQueryRefusedError,
    backend_axes,
    catalog_declarations,
    cost_posture,
    descriptor_from_backend,
    resolve_backend,
    resolve_semantic_layer,
    values_gap,
)
from .catalog import (
    MAX_DIMENSIONS,
    MAX_DIMENSIONS_PER_METRIC,
    MAX_ENTITIES,
    MAX_MEASURES,
    MAX_METRICS,
    MAX_SEMANTIC_MODELS,
    SemanticCatalog,
)
from .model import SemanticQuery, ValuesRequest
from .policy import (
    cap_columnar,
    merge_pii_meta,
    queryable_grains,
    requested_dimension_refs,
    resolve_values_request,
    screen_dimension_refs,
    screen_values_request,
    unadjudicated_refs,
    validate_grain,
    values_reach_note,
)

__all__ = [
    "DIMENSIONS_PER_DECLARATION",
    "DIMENSIONS_PER_QUERYABLE_PATH",
    "EXECUTION_DEX",
    "EXECUTION_VENDOR",
    "MAX_DIMENSIONS",
    "MAX_DIMENSIONS_PER_METRIC",
    "MAX_ENTITIES",
    "MAX_MEASURES",
    "MAX_METRICS",
    "MAX_SEMANTIC_MODELS",
    "PII_BLOCK_CONFIDENCE",
    "BackendDescriptor",
    "DimensionInfo",
    "EntityInfo",
    "EntityRole",
    "MeasureInfo",
    "MetricComposition",
    "MetricInfo",
    "SemanticBackend",
    "SemanticBackendError",
    "SemanticCatalog",
    "SemanticCatalogView",
    "SemanticLayer",
    "SemanticLayerError",
    "SemanticModelInfo",
    "SemanticQuery",
    "SemanticQueryRefusedError",
    "ValuesRequest",
    "backend_axes",
    "cap_columnar",
    "catalog_declarations",
    "cost_posture",
    "derive_entity_type",
    "descriptor_from_backend",
    "merge_element_fields",
    "merge_pii_meta",
    "qualified_dimension",
    "queryable_grains",
    "requested_dimension_refs",
    "resolve_backend",
    "resolve_semantic_layer",
    "resolve_values_request",
    "screen_dimension_refs",
    "screen_values_request",
    "unadjudicated_refs",
    "validate_grain",
    "values_gap",
    "values_reach_note",
]
